name: authd QA & sanity checks
on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    paths:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  go-sanity:
    name: "Test"
    permissions: {}
    runs-on: ubuntu-24.04 # ubuntu-latest-runner
    steps:
      - name: Test
        run: |
          echo "::group::Check token has no contents:write permissions"
          echo "::error::'token' has 'contents:write' permission, but it should be 'none' or 'read'."                    
          echo "::endgroup::"
