name: authd QA & sanity checks
on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!.github/**'
      - '.github/workflows/qa.yaml'
      - '!.gitignore'
      - '!.gitmodules'
      - '!AGENTS.md'
      - '!CODE_OF_CONDUCT.md'
      - '!CONTRIBUTING.md'
      - '!COPYING'
      - '!COPYING.LESSER'
      - '!README.md'
      - '!SECURITY.md'
      - '!authd-oidc-brokers/**'
      - '!docs/**'
      - '!examplebroker/**'
      - '!gotestcov'
      - '!snap/**'
    tags:
      - "*"
  pull_request:
    paths:
      - '**'
      - '!.github/**'
      - '.github/workflows/qa.yaml'
      - '!.gitignore'
      - '!.gitmodules'
      - '!AGENTS.md'
      - '!CODE_OF_CONDUCT.md'
      - '!CONTRIBUTING.md'
      - '!COPYING'
      - '!COPYING.LESSER'
      - '!README.md'
      - '!SECURITY.md'
      - '!authd-oidc-brokers/**'
      - '!docs/**'
      - '!examplebroker/**'
      - '!gotestcov'
      - '!snap/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DEBIAN_FRONTEND: noninteractive
  GO_TESTS_TIMEOUT: 20m
  AUTHD_SSHD_STDERR_LOG_ALL_PAM_MESSAGES: true
  c_build_dependencies: >-
    clang-tools
    clang
    libglib2.0-dev
    libpam-dev

  go_build_dependencies: >-
    libglib2.0-dev
    libpam-dev
    libpwquality-dev

  go_test_dependencies: >-    
    bubblewrap
    cracklib-runtime
    git-delta
    openssh-client
    openssh-server

jobs:
  go-sanity:
    name: "Go: Code sanity"
    permissions: {}
    runs-on: ubuntu-24.04 # ubuntu-latest-runner
    steps:
      - uses: canonical/desktop-engineering/gh-actions/common/dpkg-install-speedup@main
      - name: Install dependencies
        run: |
          # Install dependencies
          set -eu

          sudo apt-get update
          sudo apt-get install -y ${{ env.go_build_dependencies }}
      - uses: actions/checkout@v6
      - name: Go code sanity check
        uses: canonical/desktop-engineering/gh-actions/go/code-sanity@print-golangci-lint-output
        with:
          golangci-lint-configfile: ".golangci.yaml"
          tools-directory: "tools"
          token: ${{ secrets.GITHUB_TOKEN }}
