#!/bin/sh

set -eu

# In previous versions, the broker.conf was created with mode 0777 - umask.
# This is not secure, because the file can contain sensitive information
# (like the client_secret), so we ensure that the mode is 0600.
if [ -f "${SNAP_DATA}/broker.conf" ]; then
  chmod 0600 "${SNAP_DATA}/broker.conf"
fi

PREVIOUS_VERSION=$(snapctl get previous-version)

log() {
  logger -t "${SNAP_NAME}" "post-refresh: $*"
}

version_less_than() {
  output=$(semver compare "$1" "$2") || exit 1
  [ "${output}" = "less" ]
}

valid_semver() {
  if ! output=$(semver check "$1") && [ "${output}" != "invalid" ]; then
    exit 1
  fi
  [ "${output}" = "valid" ]
}

if [ -z "${PREVIOUS_VERSION}" ]; then
  log "previous-version: <not set>"
else
  log "previous-version: $PREVIOUS_VERSION"
fi
