#!/bin/sh

set -eu

# In previous versions, the broker.conf was created with mode 0777 - umask.
# This is not secure, because the file can contain sensitive information
# (like the client_secret), so we ensure that the mode is 0600.
if [ -f "${SNAP_DATA}/broker.conf" ]; then
  chmod 0600 "${SNAP_DATA}/broker.conf"
fi

PREVIOUS_VERSION=$(snapctl get previous-version)

# Important: If you add new migrations, make sure to tag the commit which
# first introduces the change, so that pre-release versions which already
# contain the change (and which were automatically uploaded to the edge channel)
# will not be migrated.
INITIAL_WORLD_READABLE_BROKER_CONF_DIR="0.5.0-pre1"

log() {
  logger -t "${SNAP_NAME}" "post-refresh: $*"
}

version_less_than() {
  output=$(semver compare "$1" "$2") || exit 1
  [ "${output}" = "less" ]
}

valid_semver() {
  if ! output=$(semver check "$1") && [ "${output}" != "invalid" ]; then
    exit 1
  fi
  [ "${output}" = "valid" ]
}

should_transition_to_world_readable_broker_conf_dir() {
  version_less_than "${PREVIOUS_VERSION}" "${INITIAL_WORLD_READABLE_BROKER_CONF_DIR}"
}

transition_to_world_readable_broker_conf_dir() {
  log "Transitioning to world-readable broker.conf.d directory"
  dir="${SNAP_DATA}/broker.conf.d"

  # shellcheck disable=SC2174 # it's fine that --mode only applies to the deepest directory, because the SNAP_DATA
  # directory is created by snapd with the correct permissions.
  mkdir -p --mode=0755 "${dir}"

  # Ensure that the files in the broker config directory are *not* world-readable,
  # because they can contain sensitive information (like the client_secret).
  find "${dir}" -type f -exec chmod 0600 {} \;

  # Change the permissions of the broker config directory itself to be world-readable,
  # so that its files can be listed by non-root users, allowing tab-completion
  # to work correctly.
  chmod 0755 "${dir}"
}

if [ -z "${PREVIOUS_VERSION}" ]; then
  log "previous-version: <not set>"
elif ! valid_semver "${PREVIOUS_VERSION}"; then
  log "previous-version: ${PREVIOUS_VERSION} (invalid semver)"
else
  log "previous-version: $PREVIOUS_VERSION"
  if should_transition_to_world_readable_broker_conf_dir; then
    transition_to_world_readable_broker_conf_dir
  fi
fi
